version: "3.8"
services:
  app:
    image: qr-service-image
    container_name: qr-code-server
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    name: main
    external: true
